import telnetlib
import time

host = "92.83.42.103"
port = int(input('give port: '))
te = telnetlib.Telnet(host, port)
te.write(b"\n")
time.sleep(3)
out = te.read_very_eager()
if b'(config)' in out:
    te.write(b'exit')
te.expect([b"IOU1#"])
te.write(b"conf t\n")
te.expect([b"IOU1\(config\)#"])
te.write(b"int eth0/0\n")
te.expect([b"IOU1\(config-if\)#"])
te.write(b"ip add 192.168.11.1 255.255.255.0\n")
te.expect([b"IOU1\(config-if\)#"])
te.write(b"no sh\n")
te.expect([b"IOU1\(config-if\)#"])
te.write(b"line vty 0 4\n")
te.expect([b"IOU1\(config-line\)#"])
te.write(b"transport input telnet\n")
te.expect([b"IOU1\(config-line\)#"])
te.write(b"password password\n")
te.expect([b"IOU1\(config-line\)#"])
te.write(b"privilege level 15\n")
te.expect([b"IOU1\(config-line\)#"])
te.write(b"exit\n")
te.expect([b"IOU1\(config\)#"])
te.write(b"exit\n")
te.expect([b"IOU1#"])
te.write(b"wr\n")
te.expect([b"\[confirm\]"])
te.write(b"\n")
